In [24]:
import pandas as pd

In [25]:
matches =  pd.read_csv("matches.csv", index_col=0)

In [26]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2024-08-17,12:30,Premier League,Matchweek 1,Sat,Away,W,2.0,0.0,Ipswich Town,...,Match Report,NaN,18.0,5.0,14.8,0.0,0,0,2024,Liverpool
1,2024-08-25,16:30,Premier League,Matchweek 2,Sun,Home,W,2.0,0.0,Brentford,...,Match Report,NaN,19.0,8.0,13.6,1.0,0,0,2024,Liverpool
2,2024-09-01,16:00,Premier League,Matchweek 3,Sun,Away,W,3.0,0.0,Manchester Utd,...,Match Report,NaN,11.0,3.0,13.4,0.0,0,0,2024,Liverpool
3,2024-09-14,15:00,Premier League,Matchweek 4,Sat,Home,L,0.0,1.0,Nott'ham Forest,...,Match Report,NaN,14.0,5.0,14.9,0.0,0,0,2024,Liverpool
4,2024-09-21,15:00,Premier League,Matchweek 5,Sat,Home,W,3.0,0.0,Bournemouth,...,Match Report,NaN,19.0,12.0,16.6,0.0,0,0,2024,Liverpool

In [27]:
matches.shape

(1918, 28)

In [28]:
38*20*3

2280

In [32]:
matches["team"].value_counts()

team
Manchester United           96
Wolverhampton Wanderers     96
Nottingham Forest           96
Chelsea                     96
Newcastle United            96
Manchester City             96
Bournemouth                 96
Aston Villa                 96
Fulham                      96
Brighton and Hove Albion    96
Brentford                   96
Tottenham Hotspur           96
Arsenal                     96
West Ham United             96
Crystal Palace              96
Liverpool                   95
Everton                     95
Leicester City              58
Southampton                 58
Luton Town                  38
Burnley                     38
Sheffield United            38
Leeds United                38
Ipswich Town                20
Name: count, dtype: int64

In [33]:
matches["round"].value_counts()

round
Matchweek 1     60
Matchweek 11    60
Matchweek 19    60
Matchweek 18    60
Matchweek 17    60
Matchweek 16    60
Matchweek 14    60
Matchweek 13    60
Matchweek 12    60
Matchweek 10    60
Matchweek 2     60
Matchweek 9     60
Matchweek 8     60
Matchweek 7     60
Matchweek 6     60
Matchweek 5     60
Matchweek 4     60
Matchweek 3     60
Matchweek 20    60
Matchweek 15    58
Matchweek 21    40
Matchweek 22    40
Matchweek 34    40
Matchweek 37    40
Matchweek 36    40
Matchweek 35    40
Matchweek 29    40
Matchweek 33    40
Matchweek 32    40
Matchweek 31    40
Matchweek 30    40
Matchweek 28    40
Matchweek 27    40
Matchweek 26    40
Matchweek 25    40
Matchweek 24    40
Matchweek 23    40
Matchweek 38    40
Name: count, dtype: int64

In [34]:
matches.dtypes

date              object
time              object
comp              object
round             object
day               object
venue             object
result            object
gf               float64
ga               float64
opponent          object
xg               float64
xga              float64
poss             float64
attendance       float64
captain           object
formation         object
opp formation     object
referee           object
match report      object
notes            float64
sh               float64
sot              float64
dist             float64
fk               float64
pk                 int64
pkatt              int64
season             int64
team              object
dtype: object

In [92]:
matches["date"] = pd.to_datetime(matches["date"], errors="coerce")

In [93]:
matches.dtypes

date             datetime64[ns]
time                     object
comp                     object
round                    object
day                      object
venue                    object
result                   object
gf                      float64
ga                      float64
opponent                 object
xg                      float64
xga                     float64
poss                    float64
attendance              float64
captain                  object
formation                object
opp formation            object
referee                  object
match report             object
notes                   float64
sh                      float64
sot                     float64
dist                    float64
fk                      float64
pk                        int64
pkatt                     int64
season                    int64
team                     object
venue_code                 int8
opp_code                   int8
hour                      int32
day_code                  int32
target                    int32
dtype: object

In [94]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [95]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [96]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [97]:
matches["day_code"] = matches["date"].dt.dayofweek

In [98]:
matches["target"] =  (matches["result"] =="W").astype("int")

In [99]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
0,2024-08-17,12:30,Premier League,Matchweek 1,Sat,Away,W,2.0,0.0,Ipswich Town,...,0.0,0,0,2024,Liverpool,0,10,12,5,1
1,2024-08-25,16:30,Premier League,Matchweek 2,Sun,Home,W,2.0,0.0,Brentford,...,1.0,0,0,2024,Liverpool,1,3,16,6,1
2,2024-09-01,16:00,Premier League,Matchweek 3,Sun,Away,W,3.0,0.0,Manchester Utd,...,0.0,0,0,2024,Liverpool,0,16,16,6,1
3,2024-09-14,15:00,Premier League,Matchweek 4,Sat,Home,L,0.0,1.0,Nott'ham Forest,...,0.0,0,0,2024,Liverpool,1,18,15,5,0
4,2024-09-21,15:00,Premier League,Matchweek 5,Sat,Home,W,3.0,0.0,Bournemouth,...,0.0,0,0,2024,Liverpool,1,2,15,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1913,2023-04-30,14:00,Premier League,Matchweek 34,Sun,Away,L,1.0,3.0,Newcastle Utd,...,0.0,0,0,2022,Southampton,0,17,14,6,0
1914,2023-05-08,20:00,Premier League,Matchweek 35,Mon,Away,L,3.0,4.0,Nott'ham Forest,...,0.0,1,1,2022,Southampton,0,18,20,0,0
1915,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Home,L,0.0,2.0,Fulham,...,0.0,0,0,2022,Southampton,1,9,15,5,0
1916,2023-05-21,14:00,Premier League,Matchweek 37,Sun,Away,L,1.0,3.0,Brighton,...,1.0,0,0,2022,Southampton,0,4,14,6,0
1917,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Home,D,4.0,4.0,Liverpool,...,1.0,0,0,2022,Southampton,1,13,16,6,0

In [149]:
from sklearn.ensemble import RandomForestClassifier

In [150]:
rf= RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [151]:
train = matches[matches["date"] < "2024-01-01"]

In [152]:
test = matches[matches["date"] > "24-01-01"]

In [153]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [154]:
matches["date"] = pd.to_datetime(matches["date"], errors="coerce")

In [155]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [156]:
preds = rf.predict(test[predictors])

In [157]:
from sklearn.metrics import accuracy_score

In [158]:
acc= accuracy_score(test["target"], preds)

In [159]:
acc

0.6866527632950991

In [192]:
combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))

In [194]:
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted    0    1
actual
0          947  237
1          364  370

In [195]:
from sklearn.metrics import precision_score

In [196]:
precision_score(test["target"], preds)

0.6095551894563427

In [197]:
grouped_matches= matches.groupby("team")

In [198]:
group = grouped_matches.get_group("Manchester City")

In [199]:
group

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
99,2024-08-18,16:30,Premier League,Matchweek 1,Sun,Away,W,2.0,0.0,Chelsea,...,0.0,0,0,2024,Manchester City,0,6,16,6,1
100,2024-08-24,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,1.0,Ipswich Town,...,1.0,1,1,2024,Manchester City,1,10,15,5,1
101,2024-08-31,17:30,Premier League,Matchweek 3,Sat,Away,W,3.0,1.0,West Ham,...,1.0,0,0,2024,Manchester City,0,22,17,5,1
102,2024-09-14,15:00,Premier League,Matchweek 4,Sat,Home,W,2.0,1.0,Brentford,...,0.0,0,0,2024,Manchester City,1,3,15,5,1
103,2024-09-22,16:30,Premier League,Matchweek 5,Sun,Home,D,2.0,2.0,Arsenal,...,1.0,0,0,2024,Manchester City,1,0,16,6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1191,2023-05-06,15:00,Premier League,Matchweek 35,Sat,Home,W,2.0,1.0,Leeds United,...,2.0,0,1,2022,Manchester City,1,11,15,5,1
1192,2023-05-14,14:00,Premier League,Matchweek 36,Sun,Away,W,3.0,0.0,Everton,...,2.0,0,0,2022,Manchester City,0,8,14,6,1
1193,2023-05-21,16:00,Premier League,Matchweek 37,Sun,Home,W,1.0,0.0,Chelsea,...,0.0,0,0,2022,Manchester City,1,6,16,6,1
1194,2023-05-24,20:00,Premier League,Matchweek 32,Wed,Away,D,1.0,1.0,Brighton,...,0.0,0,0,2022,Manchester City,0,4,20,2,0
1195,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Away,L,0.0,1.0,Brentford,...,0.0,0,0,2022,Manchester City,0,3,16,6,0

In [200]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group =  group.dropna(subset=new_cols)
    return group

In [201]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

In [202]:
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling']

In [203]:
rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
1161,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,2.0,Crystal Palace,...,5,1,3.000000,1.000000,17.666667,6.000000,17.466667,0.666667,0.333333,0.333333
1162,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6.0,0.0,Nott'ham Forest,...,2,1,3.666667,1.666667,19.333333,7.333333,15.933333,0.333333,0.000000,0.000000
1163,2022-09-03,17:30,Premier League,Matchweek 6,Sat,Away,D,1.0,1.0,Aston Villa,...,5,0,4.333333,1.666667,18.666667,8.000000,15.033333,0.333333,0.000000,0.000000
1164,2022-09-17,12:30,Premier League,Matchweek 8,Sat,Away,W,3.0,0.0,Wolves,...,5,1,3.666667,1.000000,16.000000,6.000000,15.233333,0.333333,0.000000,0.000000
1165,2022-10-02,14:00,Premier League,Matchweek 9,Sun,Home,W,6.0,3.0,Manchester Utd,...,6,1,3.333333,0.333333,15.333333,6.666667,17.000000,0.333333,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,2024-12-15,16:30,Premier League,Matchweek 16,Sun,Home,L,1.0,2.0,Manchester Utd,...,6,0,1.666667,1.333333,12.333333,4.000000,15.500000,0.333333,0.000000,0.000000
115,2024-12-21,12:30,Premier League,Matchweek 17,Sat,Away,L,1.0,2.0,Aston Villa,...,5,0,2.000000,1.333333,13.000000,4.333333,16.333333,0.333333,0.000000,0.000000
116,2024-12-26,12:30,Premier League,Matchweek 18,Thu,Home,D,1.0,1.0,Everton,...,3,0,1.333333,2.000000,11.333333,4.333333,17.400000,0.000000,0.000000,0.000000
117,2024-12-29,14:30,Premier League,Matchweek 19,Sun,Away,W,2.0,0.0,Leicester City,...,6,1,1.000000,1.666667,15.000000,4.333333,18.100000,0.333333,0.000000,0.333333
118,2025-01-04,15:00,Premier League,Matchweek 20,Sat,Home,W,4.0,1.0,West Ham,...,5,1,1.333333,1.000000,16.333333,5.000000,17.966667,0.666667,0.000000,0.333333

In [204]:
matches_rolling = matches.groupby("team"). apply(lambda x: rolling_averages(x, cols, new_cols))

In [205]:
matches_rolling

                                   date   time            comp         round  \
team
Arsenal                 1199 2022-08-27  17:30  Premier League   Matchweek 4
                        1200 2022-08-31  19:30  Premier League   Matchweek 5
                        1201 2022-09-04  16:30  Premier League   Matchweek 6
                        1202 2022-09-18  12:00  Premier League   Matchweek 8
                        1203 2022-10-01  12:30  Premier League   Matchweek 9
...                                 ...    ...             ...           ...
Wolverhampton Wanderers 333  2024-12-14  15:00  Premier League  Matchweek 16
                        334  2024-12-22  14:00  Premier League  Matchweek 17
                        335  2024-12-26  17:30  Premier League  Matchweek 18
                        336  2024-12-29  15:00  Premier League  Matchweek 19
                        337  2025-01-06  20:00  Premier League  Matchweek 20

                              day venue result   gf   ga         opponent  \
team
Arsenal                 1199  Sat  Home      W  2.0  1.0           Fulham
                        1200  Wed  Home      W  2.0  1.0      Aston Villa
                        1201  Sun  Away      L  1.0  3.0   Manchester Utd
                        1202  Sun  Away      W  3.0  0.0        Brentford
                        1203  Sat  Home      W  3.0  1.0        Tottenham
...                           ...   ...    ...  ...  ...              ...
Wolverhampton Wanderers 333   Sat  Home      L  1.0  2.0     Ipswich Town
                        334   Sun  Away      W  3.0  0.0   Leicester City
                        335   Thu  Home      W  2.0  0.0   Manchester Utd
                        336   Sun  Away      D  2.0  2.0        Tottenham
                        337   Mon  Home      L  0.0  3.0  Nott'ham Forest

                              ...  day_code  target  gf_rolling  ga_rolling  \
team                          ...
Arsenal                 1199  ...         5       1    3.000000    0.666667
                        1200  ...         2       1    3.000000    1.000000
                        1201  ...         6       0    2.333333    0.666667
                        1202  ...         6       1    1.666667    1.666667
                        1203  ...         5       1    2.000000    1.333333
...                           ...       ...     ...         ...         ...
Wolverhampton Wanderers 333   ...         5       0    1.000000    3.333333
                        334   ...         6       1    0.666667    2.666667
                        335   ...         3       1    1.666667    1.333333
                        336   ...         6       0    2.000000    0.666667
                        337   ...         0       0    2.333333    0.666667

                             sh_rolling sot_rolling dist_rolling fk_rolling  \
team
Arsenal                 1199  14.333333    5.000000    14.133333   0.333333
                        1200  18.333333    7.000000    14.433333   0.333333
                        1201  19.333333    7.333333    15.533333   0.666667
                        1202  20.000000    6.333333    16.800000   1.000000
                        1203  17.000000    6.000000    17.700000   0.666667
...                                 ...         ...          ...        ...
Wolverhampton Wanderers 333   11.666667    3.333333    19.500000   0.333333
                        334   13.666667    4.333333    19.000000   0.000000
                        335   14.333333    5.000000    16.966667   0.333333
                        336   10.333333    4.666667    19.033333   0.666667
                        337    8.666667    3.666667    19.566667   1.000000

                             pk_rolling  pkatt_rolling
team
Arsenal                 1199        0.0            0.0
                        1200        0.0            0.0
                        1201        0.0            0.0
                        1202        0.0            0.0
                        1203        0.0            0.0
...                                 ...            ...
Wolverhampton Wanderers 333         0.0            0.0
                        334         0.0            0.0
                        335         0.0            0.0
                        336         0.0            0.0
                        337         0.0            0.0

[1846 rows x 41 columns]

In [206]:
matches_rolling = matches_rolling.droplevel('team')

In [207]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
1199,2022-08-27,17:30,Premier League,Matchweek 4,Sat,Home,W,2.0,1.0,Fulham,...,5,1,3.000000,0.666667,14.333333,5.000000,14.133333,0.333333,0.0,0.0
1200,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,2.0,1.0,Aston Villa,...,2,1,3.000000,1.000000,18.333333,7.000000,14.433333,0.333333,0.0,0.0
1201,2022-09-04,16:30,Premier League,Matchweek 6,Sun,Away,L,1.0,3.0,Manchester Utd,...,6,0,2.333333,0.666667,19.333333,7.333333,15.533333,0.666667,0.0,0.0
1202,2022-09-18,12:00,Premier League,Matchweek 8,Sun,Away,W,3.0,0.0,Brentford,...,6,1,1.666667,1.666667,20.000000,6.333333,16.800000,1.000000,0.0,0.0
1203,2022-10-01,12:30,Premier League,Matchweek 9,Sat,Home,W,3.0,1.0,Tottenham,...,5,1,2.000000,1.333333,17.000000,6.000000,17.700000,0.666667,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333,2024-12-14,15:00,Premier League,Matchweek 16,Sat,Home,L,1.0,2.0,Ipswich Town,...,5,0,1.000000,3.333333,11.666667,3.333333,19.500000,0.333333,0.0,0.0
334,2024-12-22,14:00,Premier League,Matchweek 17,Sun,Away,W,3.0,0.0,Leicester City,...,6,1,0.666667,2.666667,13.666667,4.333333,19.000000,0.000000,0.0,0.0
335,2024-12-26,17:30,Premier League,Matchweek 18,Thu,Home,W,2.0,0.0,Manchester Utd,...,3,1,1.666667,1.333333,14.333333,5.000000,16.966667,0.333333,0.0,0.0
336,2024-12-29,15:00,Premier League,Matchweek 19,Sun,Away,D,2.0,2.0,Tottenham,...,6,0,2.000000,0.666667,10.333333,4.666667,19.033333,0.666667,0.0,0.0
337,2025-01-06,20:00,Premier League,Matchweek 20,Mon,Home,L,0.0,3.0,Nott'ham Forest,...,0,0,2.333333,0.666667,8.666667,3.666667,19.566667,1.000000,0.0,0.0

In [208]:
matches_rolling.index = range(matches_rolling.shape[0])

In [209]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,2022-08-27,17:30,Premier League,Matchweek 4,Sat,Home,W,2.0,1.0,Fulham,...,5,1,3.000000,0.666667,14.333333,5.000000,14.133333,0.333333,0.0,0.0
1,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,2.0,1.0,Aston Villa,...,2,1,3.000000,1.000000,18.333333,7.000000,14.433333,0.333333,0.0,0.0
2,2022-09-04,16:30,Premier League,Matchweek 6,Sun,Away,L,1.0,3.0,Manchester Utd,...,6,0,2.333333,0.666667,19.333333,7.333333,15.533333,0.666667,0.0,0.0
3,2022-09-18,12:00,Premier League,Matchweek 8,Sun,Away,W,3.0,0.0,Brentford,...,6,1,1.666667,1.666667,20.000000,6.333333,16.800000,1.000000,0.0,0.0
4,2022-10-01,12:30,Premier League,Matchweek 9,Sat,Home,W,3.0,1.0,Tottenham,...,5,1,2.000000,1.333333,17.000000,6.000000,17.700000,0.666667,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1841,2024-12-14,15:00,Premier League,Matchweek 16,Sat,Home,L,1.0,2.0,Ipswich Town,...,5,0,1.000000,3.333333,11.666667,3.333333,19.500000,0.333333,0.0,0.0
1842,2024-12-22,14:00,Premier League,Matchweek 17,Sun,Away,W,3.0,0.0,Leicester City,...,6,1,0.666667,2.666667,13.666667,4.333333,19.000000,0.000000,0.0,0.0
1843,2024-12-26,17:30,Premier League,Matchweek 18,Thu,Home,W,2.0,0.0,Manchester Utd,...,3,1,1.666667,1.333333,14.333333,5.000000,16.966667,0.333333,0.0,0.0
1844,2024-12-29,15:00,Premier League,Matchweek 19,Sun,Away,D,2.0,2.0,Tottenham,...,6,0,2.000000,0.666667,10.333333,4.666667,19.033333,0.666667,0.0,0.0
1845,2025-01-06,20:00,Premier League,Matchweek 20,Mon,Home,L,0.0,3.0,Nott'ham Forest,...,0,0,2.333333,0.666667,8.666667,3.666667,19.566667,1.000000,0.0,0.0

In [222]:
# Retraining the machine learning model

In [225]:
def make_predictions(data, predictors):
    train = data[data["date"] < "2024-01-01"]
    test = data[data["date"] > "24-01-01"]
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index = test.index)
    precision = precision_score(test["target"], preds)
    return combined, precision

In [226]:
combined, precision = make_predictions(matches_rolling, predictors + new_cols)

In [227]:
precision

0.7987220447284346

In [228]:
combined

      actual  predicted
0          1          1
1          1          1
2          0          0
3          1          1
4          1          1
...      ...        ...
1841       0          0
1842       1          0
1843       1          1
1844       0          0
1845       0          1

[1846 rows x 2 columns]

In [229]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index= True, right_index=True)

In [230]:
combined

,actual,predicted,date,team,opponent,result
0,1,1,2022-08-27,Arsenal,Fulham,W
1,1,1,2022-08-31,Arsenal,Aston Villa,W
2,0,0,2022-09-04,Arsenal,Manchester Utd,L
3,1,1,2022-09-18,Arsenal,Brentford,W
4,1,1,2022-10-01,Arsenal,Tottenham,W
...,...,...,...,...,...,...
1841,0,0,2024-12-14,Wolverhampton Wanderers,Ipswich Town,L
1842,1,0,2024-12-22,Wolverhampton Wanderers,Leicester City,W
1843,1,1,2024-12-26,Wolverhampton Wanderers,Manchester Utd,W
1844,0,0,2024-12-29,Wolverhampton Wanderers,Tottenham,D
1845,0,1,2025-01-06,Wolverhampton Wanderers,Nott'ham Forest,L

In [233]:
### Combining home and away predictions

In [236]:
class MissingDict(dict):
    __missing__ = lambda self, key: key
map_values = {
    "Brighton and Hove Albion": "Brighton",
    "Manchester United": "Manchester Utd",
    "Newcastle United": "Newcastle Utd",
    "Tottenham Hotspur": "Tottenham",
    "West Ham United": "West Ham",
    "Wolverhampton Wanderers": "Wolves"
    
}
mapping = MissingDict(**map_values)

In [237]:
mapping["Manchester United"]

'Manchester Utd'

In [238]:
combined["new_team"] = combined["team"].map(mapping)

In [239]:
combined

,actual,predicted,date,team,opponent,result,new_team
0,1,1,2022-08-27,Arsenal,Fulham,W,Arsenal
1,1,1,2022-08-31,Arsenal,Aston Villa,W,Arsenal
2,0,0,2022-09-04,Arsenal,Manchester Utd,L,Arsenal
3,1,1,2022-09-18,Arsenal,Brentford,W,Arsenal
4,1,1,2022-10-01,Arsenal,Tottenham,W,Arsenal
...,...,...,...,...,...,...,...
1841,0,0,2024-12-14,Wolverhampton Wanderers,Ipswich Town,L,Wolves
1842,1,0,2024-12-22,Wolverhampton Wanderers,Leicester City,W,Wolves
1843,1,1,2024-12-26,Wolverhampton Wanderers,Manchester Utd,W,Wolves
1844,0,0,2024-12-29,Wolverhampton Wanderers,Tottenham,D,Wolves
1845,0,1,2025-01-06,Wolverhampton Wanderers,Nott'ham Forest,L,Wolves

In [242]:
merged = combined.merge(combined, left_on=["date","new_team"], right_on=["date", "opponent"])

In [243]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,1,1,2022-08-27,Arsenal,Fulham,W,Arsenal,0,0,Fulham,Arsenal,L,Fulham
1,1,1,2022-08-31,Arsenal,Aston Villa,W,Arsenal,0,0,Aston Villa,Arsenal,L,Aston Villa
2,0,0,2022-09-04,Arsenal,Manchester Utd,L,Arsenal,1,0,Manchester United,Arsenal,W,Manchester Utd
3,1,1,2022-09-18,Arsenal,Brentford,W,Arsenal,0,0,Brentford,Arsenal,L,Brentford
4,1,1,2022-10-01,Arsenal,Tottenham,W,Arsenal,0,0,Tottenham Hotspur,Arsenal,L,Tottenham
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1702,0,0,2024-12-14,Wolverhampton Wanderers,Ipswich Town,L,Wolves,1,0,Ipswich Town,Wolves,W,Ipswich Town
1703,1,0,2024-12-22,Wolverhampton Wanderers,Leicester City,W,Wolves,0,0,Leicester City,Wolves,L,Leicester City
1704,1,1,2024-12-26,Wolverhampton Wanderers,Manchester Utd,W,Wolves,0,0,Manchester United,Wolves,L,Manchester Utd
1705,0,0,2024-12-29,Wolverhampton Wanderers,Tottenham,D,Wolves,0,1,Tottenham Hotspur,Wolves,D,Tottenham
1706,0,1,2025-01-06,Wolverhampton Wanderers,Nott'ham Forest,L,Wolves,1,0,Nottingham Forest,Wolves,W,Nottingham Forest

In [245]:
merged[(merged["predicted_x"]==1) & (merged["predicted_y"]==0)]["actual_x"].value_counts()

actual_x
1    462
0     97
Name: count, dtype: int64

In [249]:
precision

0.7987220447284346